### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by kisakiwata** [lannguyen0910/food-recognition#27]
Hi!
Your repo looks amazing.
I am trying to run inference and trying to output not just a mask, but also the labels of detection as in the examples in readme file.
But somehow when I ran the inference notebook(https://drive.google.com/file/d/1CGEtC65kvoZ-4tcqzeknGrbERvb0beuU/view?usp=sharing), it only shows the mask without including the labels. 
<img width="740" alt="Screen Shot 2023-07-06 at 16 00 52" src="https://github.com/lannguyen0910/food-recognition/assets/46466783/08480f85-050f-495f-9ef5-7f56c18df913">
If you can help me identify what I am doing wrong, that would be helpful. Thanks!

**Comment by lannguyen0910** [comment]
Hi @kisakiwata , sorry for my late response! 
There was a lack of training for the segmentation task due to the GPU limit, so the results are inferior, I recommend you train some more powerful segmentation models using this [template](https://github.com/kaylode/theseus). Moreover, I didn't implement the segmentation labels yet so the result of yours is correct. In the future, I will tackle these problems and update this repo. Thank you for your question!
