### ISSUE TITLE
Incredibly Low Accuracy

### ISSUE THREAD

**Issue by QuarterNerd** [lannguyen0910/food-recognition#29]
Hello! This repo looks great. I have tested this out on my local machine, with and without ngrok. I've noticed an abnormally low accuracy, with most pictures I try resulting in an incorrect result. This is very different from the accuracy in the README, which states an accuracy of 84.069 and a balanced accuracy of 86.033. Why would this be?

**Comment by lannguyen0910** [comment]
Thank you @QuarterNerd for your question. Sorry for my late response!

The code initially performed quite well, with detection model accuracy rates around 0.9x. Unfortunately, the initial weights, trained by a collaborator who contributed to this repository, were lost during a Drive cleanup. The results displayed in the README are based on his weights. I attempted to reproduce his results, but due to limited computational power, I was unable to train further. Consequently, the current results fluctuate around 0.6x.

This repository primarily serves as a demonstration and guide on how to create a web application for nutritional purposes. I encourage you to try training the model yourself. There are improved versions of YOLO available for you to experiment with.

> This is very different from the accuracy in the README, which states an accuracy of 84.069 and a balanced accuracy of 86.033. Why would this be?

These accuracies belong to classification models, which is correct.
